// Create a JSON list of all markdown files
export const allMarkdownFiles = [
  // 01-overview
  {
    folder: "01-overview",
    path: "01-overview/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "01-overview",
    path: "01-overview/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "01-overview",
    path: "01-overview/step12.md",
    filename: "step12.md",
    isIndex: false,
  },

  // 02-inheritance-polymorphism
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step15.md",
    filename: "step15.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step16.md",
    filename: "step16.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step17.md",
    filename: "step17.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step18.md",
    filename: "step18.md",
    isIndex: false,
  },
  {
    folder: "02-inheritance-polymorphism",
    path: "02-inheritance-polymorphism/step19.md",
    filename: "step19.md",
    isIndex: false,
  },

  // 03-adt-interface
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "03-adt-interface",
    path: "03-adt-interface/step12.md",
    filename: "step12.md",
    isIndex: false,
  },

  // 04-generics-tfd
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "04-generics-tfd",
    path: "04-generics-tfd/step15.md",
    filename: "step15.md",
    isIndex: false,
  },

  // 05-exceptions
  {
    folder: "05-exceptions",
    path: "05-exceptions/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "05-exceptions",
    path: "05-exceptions/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "05-exceptions",
    path: "05-exceptions/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "05-exceptions",
    path: "05-exceptions/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "05-exceptions",
    path: "05-exceptions/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "05-exceptions",
    path: "05-exceptions/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "05-exceptions",
    path: "05-exceptions/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "05-exceptions",
    path: "05-exceptions/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "05-exceptions",
    path: "05-exceptions/step08.md",
    filename: "step08.md",
    isIndex: false,
  },

  // 06-iterators
  {
    folder: "06-iterators",
    path: "06-iterators/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "06-iterators",
    path: "06-iterators/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "06-iterators",
    path: "06-iterators/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "06-iterators",
    path: "06-iterators/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "06-iterators",
    path: "06-iterators/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "06-iterators",
    path: "06-iterators/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "06-iterators",
    path: "06-iterators/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "06-iterators",
    path: "06-iterators/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "06-iterators",
    path: "06-iterators/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "06-iterators",
    path: "06-iterators/step09.md",
    filename: "step09.md",
    isIndex: false,
  },

  // 07-linked-list
  {
    folder: "07-linked-list",
    path: "07-linked-list/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "07-linked-list",
    path: "07-linked-list/step14.md",
    filename: "step14.md",
    isIndex: false,
  },

  // 08-ram
  {
    folder: "08-ram",
    path: "08-ram/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "08-ram",
    path: "08-ram/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "08-ram",
    path: "08-ram/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "08-ram",
    path: "08-ram/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "08-ram",
    path: "08-ram/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "08-ram",
    path: "08-ram/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "08-ram",
    path: "08-ram/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "08-ram",
    path: "08-ram/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "08-ram",
    path: "08-ram/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "08-ram",
    path: "08-ram/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "08-ram",
    path: "08-ram/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "08-ram",
    path: "08-ram/step11.md",
    filename: "step11.md",
    isIndex: false,
  },

  // 09-growth
  {
    folder: "09-growth",
    path: "09-growth/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "09-growth",
    path: "09-growth/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step15.md",
    filename: "step15.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step16.md",
    filename: "step16.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step17.md",
    filename: "step17.md",
    isIndex: false,
  },
  {
    folder: "09-growth",
    path: "09-growth/step18.md",
    filename: "step18.md",
    isIndex: false,
  },

  // 10-asymptotics
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "10-asymptotics",
    path: "10-asymptotics/step15.md",
    filename: "step15.md",
    isIndex: false,
  },

  // 11-quadratic-sorts
  {
    folder: "11-quadratic-sorts",
    path: "11-quadratic-sorts/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "11-quadratic-sorts",
    path: "11-quadratic-sorts/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "11-quadratic-sorts",
    path: "11-quadratic-sorts/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "11-quadratic-sorts",
    path: "11-quadratic-sorts/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "11-quadratic-sorts",
    path: "11-quadratic-sorts/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "11-quadratic-sorts",
    path: "11-quadratic-sorts/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "11-quadratic-sorts",
    path: "11-quadratic-sorts/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "11-quadratic-sorts",
    path: "11-quadratic-sorts/step07.md",
    filename: "step07.md",
    isIndex: false,
  },

  // 12-stack
  {
    folder: "12-stack",
    path: "12-stack/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "12-stack",
    path: "12-stack/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "12-stack",
    path: "12-stack/step13.md",
    filename: "step13.md",
    isIndex: false,
  },

  // 13-queue
  {
    folder: "13-queue",
    path: "13-queue/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "13-queue",
    path: "13-queue/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "13-queue",
    path: "13-queue/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "13-queue",
    path: "13-queue/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "13-queue",
    path: "13-queue/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "13-queue",
    path: "13-queue/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "13-queue",
    path: "13-queue/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "13-queue",
    path: "13-queue/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "13-queue",
    path: "13-queue/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "13-queue",
    path: "13-queue/step09.md",
    filename: "step09.md",
    isIndex: false,
  },

  // 14-list
  {
    folder: "14-list",
    path: "14-list/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "14-list",
    path: "14-list/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step15.md",
    filename: "step15.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step16.md",
    filename: "step16.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step17.md",
    filename: "step17.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step18.md",
    filename: "step18.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step19.md",
    filename: "step19.md",
    isIndex: false,
  },
  {
    folder: "14-list",
    path: "14-list/step20.md",
    filename: "step20.md",
    isIndex: false,
  },

  // 15-set
  {
    folder: "15-set",
    path: "15-set/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "15-set",
    path: "15-set/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "15-set",
    path: "15-set/step13.md",
    filename: "step13.md",
    isIndex: false,
  },

  // 16-bst
  {
    folder: "16-bst",
    path: "16-bst/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "16-bst",
    path: "16-bst/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "16-bst",
    path: "16-bst/step15.md",
    filename: "step15.md",
    isIndex: false,
  },

  // 17-traversal
  {
    folder: "17-traversal",
    path: "17-traversal/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step15.md",
    filename: "step15.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step16.md",
    filename: "step16.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step17.md",
    filename: "step17.md",
    isIndex: false,
  },
  {
    folder: "17-traversal",
    path: "17-traversal/step18.md",
    filename: "step18.md",
    isIndex: false,
  },

  // 18-map
  {
    folder: "18-map",
    path: "18-map/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "18-map",
    path: "18-map/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "18-map",
    path: "18-map/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "18-map",
    path: "18-map/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "18-map",
    path: "18-map/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "18-map",
    path: "18-map/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "18-map",
    path: "18-map/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "18-map",
    path: "18-map/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "18-map",
    path: "18-map/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "18-map",
    path: "18-map/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "18-map",
    path: "18-map/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "18-map",
    path: "18-map/step11.md",
    filename: "step11.md",
    isIndex: false,
  },

  // 19-avl
  {
    folder: "19-avl",
    path: "19-avl/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "19-avl",
    path: "19-avl/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "19-avl",
    path: "19-avl/step15.md",
    filename: "step15.md",
    isIndex: false,
  },

  // 20-pq
  {
    folder: "20-pq",
    path: "20-pq/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "20-pq",
    path: "20-pq/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step15.md",
    filename: "step15.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step16.md",
    filename: "step16.md",
    isIndex: false,
  },
  {
    folder: "20-pq",
    path: "20-pq/step17.md",
    filename: "step17.md",
    isIndex: false,
  },

  // 21-treap
  {
    folder: "21-treap",
    path: "21-treap/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "21-treap",
    path: "21-treap/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "21-treap",
    path: "21-treap/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "21-treap",
    path: "21-treap/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "21-treap",
    path: "21-treap/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "21-treap",
    path: "21-treap/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "21-treap",
    path: "21-treap/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "21-treap",
    path: "21-treap/step07.md",
    filename: "step07.md",
    isIndex: false,
  },

  // 22-hashing
  {
    folder: "22-hashing",
    path: "22-hashing/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step15.md",
    filename: "step15.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step16.md",
    filename: "step16.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step17.md",
    filename: "step17.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step18.md",
    filename: "step18.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step19.md",
    filename: "step19.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step20.md",
    filename: "step20.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step21.md",
    filename: "step21.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step22.md",
    filename: "step22.md",
    isIndex: false,
  },
  {
    folder: "22-hashing",
    path: "22-hashing/step23.md",
    filename: "step23.md",
    isIndex: false,
  },

  // 23-heapsort
  {
    folder: "23-heapsort",
    path: "23-heapsort/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "23-heapsort",
    path: "23-heapsort/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "23-heapsort",
    path: "23-heapsort/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "23-heapsort",
    path: "23-heapsort/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "23-heapsort",
    path: "23-heapsort/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "23-heapsort",
    path: "23-heapsort/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "23-heapsort",
    path: "23-heapsort/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "23-heapsort",
    path: "23-heapsort/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "23-heapsort",
    path: "23-heapsort/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "23-heapsort",
    path: "23-heapsort/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "23-heapsort",
    path: "23-heapsort/step10.md",
    filename: "step10.md",
    isIndex: false,
  },

  // 24-mergesort
  {
    folder: "24-mergesort",
    path: "24-mergesort/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "24-mergesort",
    path: "24-mergesort/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "24-mergesort",
    path: "24-mergesort/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "24-mergesort",
    path: "24-mergesort/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "24-mergesort",
    path: "24-mergesort/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "24-mergesort",
    path: "24-mergesort/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "24-mergesort",
    path: "24-mergesort/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "24-mergesort",
    path: "24-mergesort/step07.md",
    filename: "step07.md",
    isIndex: false,
  },

  // 25-quicksort
  {
    folder: "25-quicksort",
    path: "25-quicksort/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "25-quicksort",
    path: "25-quicksort/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "25-quicksort",
    path: "25-quicksort/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "25-quicksort",
    path: "25-quicksort/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "25-quicksort",
    path: "25-quicksort/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "25-quicksort",
    path: "25-quicksort/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "25-quicksort",
    path: "25-quicksort/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "25-quicksort",
    path: "25-quicksort/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "25-quicksort",
    path: "25-quicksort/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "25-quicksort",
    path: "25-quicksort/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "25-quicksort",
    path: "25-quicksort/step10.md",
    filename: "step10.md",
    isIndex: false,
  },

  // 26-graph
  {
    folder: "26-graph",
    path: "26-graph/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "26-graph",
    path: "26-graph/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step13.md",
    filename: "step13.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step14.md",
    filename: "step14.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step15.md",
    filename: "step15.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step16.md",
    filename: "step16.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step17.md",
    filename: "step17.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step18.md",
    filename: "step18.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step19.md",
    filename: "step19.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step20.md",
    filename: "step20.md",
    isIndex: false,
  },
  {
    folder: "26-graph",
    path: "26-graph/step21.md",
    filename: "step21.md",
    isIndex: false,
  },

  // 27-graph-search
  {
    folder: "27-graph-search",
    path: "27-graph-search/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step10.md",
    filename: "step10.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step11.md",
    filename: "step11.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step12.md",
    filename: "step12.md",
    isIndex: false,
  },
  {
    folder: "27-graph-search",
    path: "27-graph-search/step13.md",
    filename: "step13.md",
    isIndex: false,
  },

  // 28-shortest-path
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "28-shortest-path",
    path: "28-shortest-path/step10.md",
    filename: "step10.md",
    isIndex: false,
  },

  // 29-mst
  {
    folder: "29-mst",
    path: "29-mst/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "29-mst",
    path: "29-mst/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "29-mst",
    path: "29-mst/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "29-mst",
    path: "29-mst/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "29-mst",
    path: "29-mst/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "29-mst",
    path: "29-mst/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "29-mst",
    path: "29-mst/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "29-mst",
    path: "29-mst/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "29-mst",
    path: "29-mst/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "29-mst",
    path: "29-mst/step09.md",
    filename: "step09.md",
    isIndex: false,
  },

  // 30-union-find
  {
    folder: "30-union-find",
    path: "30-union-find/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "30-union-find",
    path: "30-union-find/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "30-union-find",
    path: "30-union-find/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "30-union-find",
    path: "30-union-find/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "30-union-find",
    path: "30-union-find/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "30-union-find",
    path: "30-union-find/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "30-union-find",
    path: "30-union-find/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "30-union-find",
    path: "30-union-find/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "30-union-find",
    path: "30-union-find/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "30-union-find",
    path: "30-union-find/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
  {
    folder: "30-union-find",
    path: "30-union-find/step10.md",
    filename: "step10.md",
    isIndex: false,
  },

  // 31-linear-sort
  {
    folder: "31-linear-sort",
    path: "31-linear-sort/index.md",
    filename: "index.md",
    isIndex: true,
  },
  {
    folder: "31-linear-sort",
    path: "31-linear-sort/step01.md",
    filename: "step01.md",
    isIndex: false,
  },
  {
    folder: "31-linear-sort",
    path: "31-linear-sort/step02.md",
    filename: "step02.md",
    isIndex: false,
  },
  {
    folder: "31-linear-sort",
    path: "31-linear-sort/step03.md",
    filename: "step03.md",
    isIndex: false,
  },
  {
    folder: "31-linear-sort",
    path: "31-linear-sort/step04.md",
    filename: "step04.md",
    isIndex: false,
  },
  {
    folder: "31-linear-sort",
    path: "31-linear-sort/step05.md",
    filename: "step05.md",
    isIndex: false,
  },
  {
    folder: "31-linear-sort",
    path: "31-linear-sort/step06.md",
    filename: "step06.md",
    isIndex: false,
  },
  {
    folder: "31-linear-sort",
    path: "31-linear-sort/step07.md",
    filename: "step07.md",
    isIndex: false,
  },
  {
    folder: "31-linear-sort",
    path: "31-linear-sort/step08.md",
    filename: "step08.md",
    isIndex: false,
  },
  {
    folder: "31-linear-sort",
    path: "31-linear-sort/step09.md",
    filename: "step09.md",
    isIndex: false,
  },
];
